frontendUrl: "https://app.moneylytics.io"

service:
  type: ClusterIP

frontend:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: app.moneylytics.io
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - app.moneylytics.io
        secretName: moneylytics-app-tls
