frontendUrl: "http://moneylytics.io"

service:
  type: ClusterIP

frontend:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: moneylytics.io
        paths:
          - path: /
            pathType: Prefix
