config:
  clients:
    - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push

  snippets:
    pipelineStages:
      - cri: {}
      - json:
          expressions:
            log_level: '["log.level"]'
            message: message
            service_name: '["service.name"]'
            logger: '["log.logger"]'
      - labels:
          log_level:
          service_name:
      - output:
          source: message

    scrapeConfigs: |
      - job_name: moneylytics-pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - moneylytics
                - moneylytics-stage
        pipeline_stages:
          - cri: {}
          - json:
              expressions:
                log_level: '["log.level"]'
                message: message
                service_name: '["service.name"]'
                logger: '["log.logger"]'
          - labels:
              log_level:
              service_name:
          - output:
              source: message
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: moneylytics-api
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
