-- 1. New tables
CREATE TABLE organizations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE organization_members (
    organization_id BIGINT      NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    user_id         BIGINT      NOT NULL REFERENCES users (id)         ON DELETE CASCADE,
    role            VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    joined_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (organization_id, user_id)
);

-- 2. Add organization_id column to all user-data tables (nullable first)
ALTER TABLE accounts                          ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE transactions                      ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE budgets                           ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE thresholds                        ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE collections                       ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE categories                        ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE transaction_groups                ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE ignored_transactions              ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE recurring_series                  ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE recurring_false_positive          ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE recurring_sync_log                ADD COLUMN organization_id BIGINT REFERENCES organizations (id);
ALTER TABLE csv_profiles                      ADD COLUMN organization_id BIGINT;
ALTER TABLE recurring_classifier_token_counts ADD COLUMN organization_id BIGINT;
ALTER TABLE recurring_classifier_class_counts ADD COLUMN organization_id BIGINT;

-- 3. Create one auto-org per existing user
INSERT INTO organizations (name)
    SELECT 'Persönlich' FROM users ORDER BY id;

-- 4. Map each user to their auto-org (matching by insertion order via ROW_NUMBER)
WITH numbered_users AS (
    SELECT id AS user_id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM users
),
numbered_orgs AS (
    SELECT id AS org_id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM organizations
)
INSERT INTO organization_members (organization_id, user_id, role)
    SELECT no.org_id, nu.user_id, 'OWNER'
    FROM numbered_users nu
    JOIN numbered_orgs no ON no.rn = nu.rn;

-- 5. Backfill organization_id from user_id in all data tables
UPDATE accounts SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = accounts.user_id AND om.role = 'OWNER'
);
UPDATE transactions SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = transactions.user_id AND om.role = 'OWNER'
);
UPDATE budgets SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = budgets.user_id AND om.role = 'OWNER'
);
UPDATE thresholds SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = thresholds.user_id AND om.role = 'OWNER'
);
UPDATE collections SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = collections.user_id AND om.role = 'OWNER'
);
UPDATE categories SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = categories.user_id AND om.role = 'OWNER'
);
UPDATE transaction_groups SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = transaction_groups.user_id AND om.role = 'OWNER'
);
UPDATE ignored_transactions SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = ignored_transactions.user_id AND om.role = 'OWNER'
);
UPDATE recurring_series SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = recurring_series.user_id AND om.role = 'OWNER'
);
UPDATE recurring_false_positive SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = recurring_false_positive.user_id AND om.role = 'OWNER'
);
UPDATE recurring_sync_log SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = recurring_sync_log.user_id AND om.role = 'OWNER'
);
UPDATE csv_profiles SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = csv_profiles.user_id AND om.role = 'OWNER'
);
UPDATE recurring_classifier_token_counts SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = recurring_classifier_token_counts.user_id AND om.role = 'OWNER'
);
UPDATE recurring_classifier_class_counts SET organization_id = (
    SELECT om.organization_id FROM organization_members om WHERE om.user_id = recurring_classifier_class_counts.user_id AND om.role = 'OWNER'
);

-- 6. Make organization_id NOT NULL
ALTER TABLE accounts                          ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE transactions                      ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE budgets                           ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE thresholds                        ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE collections                       ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE categories                        ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE transaction_groups                ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE ignored_transactions              ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE recurring_series                  ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE recurring_false_positive          ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE recurring_sync_log                ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE csv_profiles                      ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE recurring_classifier_token_counts ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE recurring_classifier_class_counts ALTER COLUMN organization_id SET NOT NULL;

-- 7. Update unique constraints that included user_id
ALTER TABLE accounts DROP CONSTRAINT IF EXISTS accounts_iban_user_id_key;
ALTER TABLE accounts ADD CONSTRAINT accounts_iban_organization_id_key UNIQUE (iban, organization_id);

ALTER TABLE ignored_transactions DROP CONSTRAINT IF EXISTS ignored_transactions_fingerprint_user_id_key;
ALTER TABLE ignored_transactions ADD CONSTRAINT ignored_transactions_fingerprint_organization_id_key UNIQUE (fingerprint, organization_id);
