CREATE TABLE organization_invitations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     BIGINT       NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    email               VARCHAR(255) NOT NULL,
    token               VARCHAR(64)  NOT NULL UNIQUE,
    role                VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    created_by_user_id  BIGINT REFERENCES users (id),
    created_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at          TIMESTAMP    NOT NULL,
    accepted_at         TIMESTAMP,
    accepted_by_user_id BIGINT REFERENCES users (id)
);
