CREATE TABLE category_merge (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_category_id BIGINT,
    source_name        VARCHAR NOT NULL,
    source_parent_id   BIGINT,
    target_category_id BIGINT  NOT NULL REFERENCES category(id),
    organization_id    BIGINT  NOT NULL REFERENCES organization(id),
    merged_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    reverted_at        TIMESTAMP
);

CREATE TABLE category_merge_transaction (
    merge_id       BIGINT NOT NULL REFERENCES category_merge(id),
    transaction_id BIGINT NOT NULL,
    PRIMARY KEY (merge_id, transaction_id)
);

CREATE TABLE category_merge_child (
    merge_id          BIGINT NOT NULL REFERENCES category_merge(id),
    child_category_id BIGINT NOT NULL,
    PRIMARY KEY (merge_id, child_category_id)
);
