CREATE TABLE transaction_import (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT       NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
    imported_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    filename          VARCHAR(500) NOT NULL,
    checksum          VARCHAR(64)  NOT NULL,
    file_type         VARCHAR(10)  NOT NULL,
    transaction_count INT          NOT NULL DEFAULT 0,
    status            VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE'
);

CREATE INDEX idx_transaction_import_org ON transaction_import(organization_id);

ALTER TABLE transaction ADD COLUMN import_id BIGINT REFERENCES transaction_import(id) ON DELETE SET NULL;

CREATE INDEX idx_transaction_import_id ON transaction(import_id);
