create sequence collections_id_seq;
create sequence transaction_groups_id_seq;
create sequence transaction_offsets_id_seq;

create table public.csv_profile
(
    id              bigint generated by default as identity
        constraint csv_profiles_pkey
            primary key,
    fingerprint     varchar(255) not null,
    mapping_json    text         not null,
    organization_id bigint       not null
);

alter table public.csv_profile
    owner to moneylytics;

create table public.organization
(
    id                bigint generated by default as identity
        constraint organizations_pkey
            primary key,
    created_at        timestamp(6) with time zone not null,
    name              varchar(255)                not null,
    logo_data         bytea,
    logo_content_type varchar(100)
);

alter table public.organization
    owner to moneylytics;

create table public.account
(
    id              bigint generated by default as identity
        constraint accounts_pkey
            primary key,
    iban            varchar(255) not null,
    name            varchar(255) not null,
    balance         numeric(19, 4),
    balance_date    date,
    organization_id bigint       not null
        constraint accounts_organization_id_fkey
            references public.organization,
    constraint accounts_iban_organization_id_key
        unique (iban, organization_id),
    constraint ukaic8rybpygomla3bha46uj9x6
        unique (iban, organization_id),
    constraint uknut0kwlddxigmk8knb4nlhvi6
        unique (iban, organization_id)
);

alter table public.account
    owner to moneylytics;

create table public.budget
(
    id              bigint generated by default as identity
        constraint budgets_pkey
            primary key,
    name            varchar(255) not null,
    note            text,
    target_amount   numeric(19, 2),
    organization_id bigint       not null
        constraint budgets_organization_id_fkey
            references public.organization
);

alter table public.budget
    owner to moneylytics;

create table public.category
(
    id              bigint generated by default as identity
        constraint categories_pkey
            primary key,
    name            varchar(255) not null,
    category_group  varchar(255),
    organization_id bigint       not null
        constraint categories_organization_id_fkey
            references public.organization,
    parent_id       bigint
        constraint fk_category_parent
            references public.category
);

alter table public.category
    owner to moneylytics;

create unique index categories_unique_idx
    on public.category (organization_id, COALESCE(parent_id, '-1'::integer::bigint), name);

create table public.category_classifier_class_count
(
    id              bigint generated always as identity
        primary key,
    organization_id bigint           not null
        references public.organization,
    category_id     bigint           not null
        references public.category
            on delete cascade,
    count           bigint default 1 not null,
    constraint uq_cat_clf_class
        unique (organization_id, category_id)
);

alter table public.category_classifier_class_count
    owner to moneylytics;

create table public.category_classifier_token_count
(
    id              bigint generated always as identity
        primary key,
    organization_id bigint           not null
        references public.organization,
    category_id     bigint           not null
        references public.category
            on delete cascade,
    token           varchar(255)     not null,
    count           bigint default 1 not null,
    constraint uq_cat_clf_token
        unique (organization_id, category_id, token)
);

alter table public.category_classifier_token_count
    owner to moneylytics;

create table public.category_merge
(
    id                 bigint generated by default as identity
        primary key,
    source_category_id bigint,
    source_name        varchar(255)            not null,
    source_parent_id   bigint,
    target_category_id bigint                  not null
        references public.category,
    organization_id    bigint                  not null
        references public.organization,
    merged_at          timestamp default now() not null,
    reverted_at        timestamp
);

alter table public.category_merge
    owner to moneylytics;

create table public.category_merge_child
(
    merge_id          bigint not null
        references public.category_merge,
    child_category_id bigint not null,
    primary key (merge_id, child_category_id)
);

alter table public.category_merge_child
    owner to moneylytics;

create table public.category_merge_transaction
(
    merge_id       bigint not null
        references public.category_merge,
    transaction_id bigint not null,
    primary key (merge_id, transaction_id)
);

alter table public.category_merge_transaction
    owner to moneylytics;

create table public.collection
(
    id              bigint  default nextval('collections_id_seq'::regclass) not null
        constraint collections_pkey
            primary key,
    name            varchar(255)                                            not null,
    note            text,
    organization_id bigint                                                  not null
        constraint collections_organization_id_fkey
            references public.organization,
    archived        boolean default false                                   not null
);

alter table public.collection
    owner to moneylytics;

create table public.ignored_transaction
(
    id              bigint generated by default as identity
        constraint ignored_transactions_pkey
            primary key,
    fingerprint     varchar(64) not null,
    organization_id bigint      not null
        constraint fkg4i2pkc4sw7yfn6ru0re6mtux
            references public.organization,
    constraint ignored_transactions_fingerprint_organization_id_key
        unique (fingerprint, organization_id),
    constraint uk6qcc86r74gvsgeuwcww9g5n4t
        unique (fingerprint, organization_id),
    constraint uksg9mw6i0glt76atjkjbv7mml8
        unique (fingerprint, organization_id)
);

alter table public.ignored_transaction
    owner to moneylytics;

create table public.recurring_classifier_class_count
(
    id              bigint  default nextval('recurring_classifier_class_counts_id_seq'::regclass) not null
        constraint recurring_classifier_class_counts_pkey
            primary key,
    type            varchar(50)                                                                   not null,
    count           integer default 0                                                             not null,
    organization_id bigint                                                                        not null
);

alter table public.recurring_classifier_class_count
    owner to moneylytics;

create table public.recurring_classifier_token_count
(
    id              bigint  default nextval('recurring_classifier_token_counts_id_seq'::regclass) not null
        constraint recurring_classifier_token_counts_pkey
            primary key,
    type            varchar(50)                                                                   not null,
    token           varchar(100)                                                                  not null,
    count           integer default 0                                                             not null,
    organization_id bigint                                                                        not null
);

alter table public.recurring_classifier_token_count
    owner to moneylytics;

create table public.recurring_false_positive
(
    id              bigserial
        primary key,
    fingerprint     varchar(512) not null,
    created_at      date         not null,
    organization_id bigint       not null
        constraint fktfhn01157fqs8xfpe318rq4g2
            references public.organization
);

alter table public.recurring_false_positive
    owner to moneylytics;

create table public.recurring_series
(
    id                 bigserial
        primary key,
    label              varchar(255)                               not null,
    type               varchar(255)                               not null,
    direction          varchar(255)                               not null,
    cadence            varchar(255)                               not null,
    interval_days      integer                                    not null,
    expected_amount    numeric(19, 4)                             not null,
    amount_variable    boolean                                    not null,
    currency           varchar(3)                                 not null,
    account_iban       varchar(255)                               not null,
    first_seen         date                                       not null,
    last_seen          date                                       not null,
    occurrence_count   integer                                    not null,
    next_expected_date date                                       not null,
    status             varchar(255)                               not null,
    fingerprint        varchar(512) default ''::character varying not null,
    organization_id    bigint                                     not null
        constraint fkj2bk1qnhaws1kiab5c33njvgw
            references public.organization
);

alter table public.recurring_series
    owner to moneylytics;

create table public.recurring_sync_log
(
    id                        bigserial
        primary key,
    ran_at                    timestamp                                           not null,
    series_updated_count      integer      default 0                              not null,
    transactions_linked_count integer      default 0                              not null,
    triggered_by              varchar(255) default 'SCHEDULED'::character varying not null,
    organization_id           bigint                                              not null
        constraint fkt8qxk0kls55irhmpp4oncpd2t
            references public.organization
);

alter table public.recurring_sync_log
    owner to moneylytics;

create table public.spring_session
(
    primary_id            char(36) not null
        constraint spring_session_pk
            primary key,
    session_id            char(36) not null,
    creation_time         bigint   not null,
    last_access_time      bigint   not null,
    max_inactive_interval integer  not null,
    expiry_time           bigint   not null,
    principal_name        varchar(100)
);

alter table public.spring_session
    owner to moneylytics;

create unique index spring_session_ix1
    on public.spring_session (session_id);

create index spring_session_ix2
    on public.spring_session (expiry_time);

create index spring_session_ix3
    on public.spring_session (principal_name);

create table public.spring_session_attributes
(
    session_primary_id char(36)     not null
        constraint spring_session_attributes_fk
            references public.spring_session
            on delete cascade,
    attribute_name     varchar(200) not null,
    attribute_bytes    bytea        not null,
    constraint spring_session_attributes_pk
        primary key (session_primary_id, attribute_name)
);

alter table public.spring_session_attributes
    owner to moneylytics;

create table public.threshold
(
    id              bigint generated by default as identity
        constraint thresholds_pkey
            primary key,
    category        varchar(255),
    critical        numeric(19, 2),
    notice          numeric(19, 2),
    period          varchar(255) not null
        constraint thresholds_period_check
            check ((period)::text = ANY
                   (ARRAY [('WEEKLY'::character varying)::text, ('MONTHLY'::character varying)::text, ('QUARTERLY'::character varying)::text, ('YEARLY'::character varying)::text])),
    subcategory     varchar(255),
    warning         numeric(19, 2),
    category_group  varchar(255),
    organization_id bigint       not null
        constraint thresholds_organization_id_fkey
            references public.organization,
    group_name      varchar(255),
    category_id     bigint
        references public.category
);

alter table public.threshold
    owner to moneylytics;

create table public.tier
(
    id              bigint generated always as identity
        primary key,
    name            varchar(100)          not null
        unique,
    description     varchar(500),
    active          boolean default true  not null,
    is_default      boolean default false not null,
    stripe_price_id varchar(255)
        unique
);

alter table public.tier
    owner to moneylytics;

create unique index uq_tier_is_default
    on public.tier (is_default)
    where (is_default = true);

create table public.transaction
(
    id                bigint generated by default as identity
        constraint transactions_pkey
            primary key,
    amount            numeric(19, 4)        not null,
    booking_date      date                  not null,
    currency          varchar(3)            not null,
    fingerprint       varchar(64),
    value_date        date                  not null,
    account_id        bigint                not null
        constraint fk20w7wsg13u9srbq3bd7chfxdh
            references public.account,
    comment           varchar(1000),
    purpose           varchar(2000),
    accounting_date   date                  not null,
    counterparty_name varchar(255),
    counterparty_iban varchar(34),
    organization_id   bigint                not null
        constraint transactions_organization_id_fkey
            references public.organization,
    parent_id         bigint
        references public.transaction
            on delete restrict,
    is_virtual        boolean default false not null,
    excluded          boolean default false not null,
    category_id       bigint
        constraint fkgik7ruym8r1n4xngrclc6kiih
            references public.category,
    constraint uktlko6dnlc3ds2jcop242s59da
        unique (fingerprint, account_id)
);

alter table public.transaction
    owner to moneylytics;

create table public.budget_transaction
(
    id             bigint generated by default as identity
        constraint budget_transactions_pkey
            primary key,
    amount         numeric(19, 2),
    budget_id      bigint not null
        constraint fktaxcwbfp5j7i1fgkmdalxhqi6
            references public.budget
            on delete cascade,
    transaction_id bigint not null
        constraint fkplp74sn4k7dj24nseg4jvwc2s
            references public.transaction
            on delete cascade,
    constraint uk5lh02hxaa618t60hcytmjq0h3
        unique (budget_id, transaction_id),
    constraint ukpvqdpkyv764djk746o95hdoq5
        unique (budget_id, transaction_id)
);

alter table public.budget_transaction
    owner to moneylytics;

create table public.collection_transaction
(
    collection_id  bigint not null
        constraint collection_transactions_collection_id_fkey
            references public.collection
            on delete cascade,
    transaction_id bigint not null
        constraint collection_transactions_transaction_id_fkey
            references public.transaction
            on delete cascade,
    constraint collection_transactions_pkey
        primary key (collection_id, transaction_id)
);

alter table public.collection_transaction
    owner to moneylytics;

create table public.recurring_series_member
(
    id             bigserial
        primary key,
    series_id      bigint not null
        references public.recurring_series,
    transaction_id bigint not null
        references public.transaction
);

alter table public.recurring_series_member
    owner to moneylytics;

create table public.recurring_sync_log_entry
(
    id                bigserial
        primary key,
    log_id            bigint         not null
        references public.recurring_sync_log,
    series_id         bigint,
    series_label      varchar(255)   not null,
    transaction_id    bigint         not null
        references public.transaction,
    booking_date      date           not null,
    amount            numeric(19, 4) not null,
    counterparty_name varchar(255)
);

alter table public.recurring_sync_log_entry
    owner to moneylytics;

create index idx_transaction_parent_id
    on public.transaction (parent_id);

create table public.transaction_group
(
    id              bigint default nextval('transaction_groups_id_seq'::regclass) not null
        constraint transaction_groups_pkey
            primary key,
    name            varchar(255),
    comment         text,
    organization_id bigint                                                        not null
        constraint transaction_groups_organization_id_fkey
            references public.organization
);

alter table public.transaction_group
    owner to moneylytics;

create table public.transaction_group_member
(
    group_id       bigint not null,
    transaction_id bigint not null,
    constraint transaction_group_members_pkey
        primary key (group_id, transaction_id)
);

alter table public.transaction_group_member
    owner to moneylytics;

create table public.transaction_offset
(
    id               bigint default nextval('transaction_offsets_id_seq'::regclass) not null
        constraint transaction_offsets_pkey
            primary key,
    transaction_a_id bigint                                                         not null
        constraint transaction_offsets_transaction_a_id_fkey
            references public.transaction
            on delete cascade,
    transaction_b_id bigint                                                         not null
        constraint transaction_offsets_transaction_b_id_fkey
            references public.transaction
            on delete cascade,
    amount_a         numeric(19, 4),
    group_id         bigint,
    amount_b         numeric(19, 4),
    comment          text,
    constraint uk7d8c63dh20msfyrwcqx4aq39s
        unique (transaction_a_id, transaction_b_id),
    constraint uk8gdnftytdaxhxh6wep1eoyv3v
        unique (transaction_a_id, transaction_b_id),
    constraint uq_transaction_offsets
        unique (transaction_a_id, transaction_b_id)
);

alter table public.transaction_offset
    owner to moneylytics;

create table public."user"
(
    id                        bigint generated by default as identity
        constraint users_pkey
            primary key,
    external_id               varchar(255)                                  not null
        constraint ukcup9hom3h5cte4btcq935d0uu
            unique,
    password_hash             varchar(255),
    default_account_id        bigint
        constraint users_default_account_id_fkey
            references public.account
            on delete set null,
    language                  varchar(10),
    transactions_column_order varchar(500),
    role                      varchar(20) default 'USER'::character varying not null,
    tier_id                   bigint                                        not null
        references public.tier
);

alter table public."user"
    owner to moneylytics;

create table public.invoice
(
    id                bigint generated always as identity
        primary key,
    user_id           bigint                                      not null
        references public."user",
    stripe_invoice_id varchar(255)
        unique,
    amount_cents      integer                                     not null,
    currency          varchar(3) default 'eur'::character varying not null,
    status            varchar(50)                                 not null,
    period_start      timestamp                                   not null,
    period_end        timestamp                                   not null,
    pdf_data          bytea,
    issued_at         timestamp                                   not null,
    invoice_number    varchar(100)
);

alter table public.invoice
    owner to moneylytics;

create table public.organization_invitation
(
    id                  bigint generated by default as identity
        constraint organization_invitations_pkey
            primary key,
    organization_id     bigint                                          not null
        constraint organization_invitations_organization_id_fkey
            references public.organization
            on delete cascade,
    email               varchar(255)                                    not null,
    token               varchar(64)                                     not null
        constraint organization_invitations_token_key
            unique,
    role                varchar(20) default 'MEMBER'::character varying not null,
    created_by_user_id  bigint
        constraint organization_invitations_created_by_user_id_fkey
            references public."user",
    created_at          timestamp   default CURRENT_TIMESTAMP           not null,
    expires_at          timestamp                                       not null,
    accepted_at         timestamp,
    accepted_by_user_id bigint
        constraint organization_invitations_accepted_by_user_id_fkey
            references public."user"
);

alter table public.organization_invitation
    owner to moneylytics;

create table public.organization_member
(
    organization_id bigint                      not null
        constraint fk7vpc2vd3jlfahlombjdc32mhe
            references public.organization,
    user_id         bigint                      not null
        constraint fk67edx4b35ogkpk3ghbhwand9i
            references public."user",
    joined_at       timestamp(6) with time zone not null,
    role            varchar(20)                 not null
        constraint organization_members_role_check
            check ((role)::text = ANY
                   (ARRAY [('MEMBER'::character varying)::text, ('ADMIN'::character varying)::text, ('OWNER'::character varying)::text])),
    constraint organization_members_pkey
        primary key (organization_id, user_id)
);

alter table public.organization_member
    owner to moneylytics;

create table public.stripe_customer
(
    id                     bigint generated always as identity
        primary key,
    user_id                bigint       not null
        unique
        references public."user",
    stripe_customer_id     varchar(255) not null
        unique,
    stripe_subscription_id varchar(255),
    subscription_status    varchar(50),
    current_period_end     bigint,
    price_id               varchar(255),
    current_period_start   bigint
);

alter table public.stripe_customer
    owner to moneylytics;

create table public.transaction_labels
(
    id           bigint generated by default as identity
        primary key,
    amount       numeric(38, 2)              not null,
    booking_date date                        not null,
    category     varchar(255)                not null,
    created_at   timestamp(6) with time zone not null,
    purpose      varchar(2000),
    source       varchar(255)                not null,
    subcategory  varchar(255)                not null,
    user_id      bigint                      not null
        constraint fk74fyplm188n92utqucsjjml4p
            references public."user"
);

alter table public.transaction_labels
    owner to moneylytics;
