create table transaction_import
(
    id              bigint generated by default as identity primary key,
    organization_id bigint                                          not null
        references organization on delete cascade,
    imported_at     timestamp   default CURRENT_TIMESTAMP           not null,
    status          varchar(10) default 'ACTIVE'                    not null
);
create index idx_transaction_import_org on transaction_import (organization_id);

create table import_file
(
    id                bigint generated always as identity primary key,
    import_id         bigint                                          not null
        references transaction_import on delete cascade,
    filename          varchar(500)                                    not null,
    checksum          varchar(64)                                     not null,
    file_type         varchar(10)                                     not null,
    transaction_count integer     default 0                           not null,
    status            varchar(10) default 'ACTIVE'                    not null
);
create index idx_import_file_import_id on import_file (import_id);

create table import_preview_session
(
    id         uuid      not null primary key,
    rows_json  text      not null,
    expires_at timestamp not null
);

alter table transaction
    add column import_id      bigint references transaction_import on delete set null,
    add column import_file_id bigint references import_file on delete set null;

create index idx_transaction_import_id      on transaction (import_id);
create index idx_transaction_import_file_id on transaction (import_file_id);
