apiVersion: v1
kind: Service
metadata:
  name: {{ include "moneylytics.fullname" . }}-frontend
  labels:
    {{- include "moneylytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "moneylytics.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
