apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "moneylytics.fullname" . }}-frontend
  labels:
    {{- include "moneylytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "moneylytics.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "moneylytics.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: BACKEND_URL
              value: "http://{{ include "moneylytics.fullname" . }}:{{ .Values.service.port }}"
