apiVersion: v1
kind: Service
metadata:
  name: {{ include "moneylytics.fullname" . }}-postgres
  labels:
    {{- include "moneylytics.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    {{- include "moneylytics.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
