apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "moneylytics.fullname" . }}-postgres-data
  labels:
    {{- include "moneylytics.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage | quote }}
