apiVersion: v1
kind: Secret
metadata:
  name: {{ include "moneylytics.fullname" . }}-postgres
  labels:
    {{- include "moneylytics.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
